version: "3.8"

networks:
  cdb-net:
    name: cdb-net
    driver: bridge

services:
  db:
    image: postgres
    container_name: customer
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=customer
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
